In [1]:
import numpy as np
arry = np.array([1,2,3,4,5,6,7,8,9,10])
cube = arry ** 3  # vector9zed operations on numpy

In [2]:
print(cube)

[   1    8   27   64  125  216  343  512  729 1000]


In [3]:
# boradcasting
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 * arr2  # Broadcasting arr2 across arr1
print(result)
# Output: of + operation.
# [[2 4 6]
#  [5 7 9]]

[[ 1  4  9]
 [ 4 10 18]]


In [4]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)


[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [5]:
max_array = np.array([[1,2,3],
                      [4,5,6], # performing max function on 2D array
                     [8,12,16]])
result = max_array.max(axis=0)  # columwise max element in the array
print(result)

[ 8 12 16]


In [6]:
kishore = np.array([1,2,3,4,5,6,7,8])
result = kishore * 10
print(result)   # broadcasting 

[10 20 30 40 50 60 70 80]


In [7]:
variance = data.var(axis=0)
print(variance)

[50. 50. 50.]


In [8]:

equal = np.linspace(1,100,5) #
print(equal)

[  1.    25.75  50.5   75.25 100.  ]


In [9]:
gopal = np.array([10,20,30,40,50])
gopal.var()

200.0

In [25]:


students = np.array([
    [85, 78, 92],  # Student 1
    [70, 88, 80],  # Student 2
    [90, 95, 94],  # Student 3
    [60, 65, 70],  # Student 4
    [75, 80, 85]   # Student 5
])

names = np.array(['Ravi', 'Simran', 'Amit', 'Pooja', 'Neha'])
subjects = np.array(['Maths', 'Science', 'English'])


In [29]:
total = students.sum(axis=1)
averages = students.mean(axis=1)


In [33]:
print(total)

[255 238 279 195 240]


In [35]:
topper_index = np.argmax(total) # index of maximum marks
print("topper is :", names[topper_index])
print(topper_index)

topper is : Amit
2


In [45]:
# subject wise topper
english_topper = np.argmax(students[:,2])
print("english topper is :", names[english_topper])

2


In [100]:
variance = np.var(students[:,1])
print("variance of science marks:", variance)

variance of science marks: 102.16
