In [24]:
import numpy as np

In [15]:
np.zeros((3,4)) # three rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.full((3,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [27]:
np.eye(5)  # to create identity matrices


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.arange(1,100,8)

array([ 1,  9, 17, 25, 33, 41, 49, 57, 65, 73, 81, 89, 97])

In [39]:
arr1 = np.array([[1,3,4],[2,3,5]])# 2d array


array([[1, 3, 4],
       [2, 3, 5]])

In [41]:
np.linspace(1,100,5) # evenly spaced array deta hain 

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [13]:
myarr = np.array([[1,3,4],[6,7,8],[9,3,12],[21,13,29]], dtype = 'float32') # setting data type specifically

In [55]:
myarr

array([[ 1.,  3.,  4.],
       [ 6.,  7.,  8.],
       [ 9.,  3., 12.],
       [21., 13., 29.]], dtype=float32)

In [57]:
n = myarr.astype('float64') # changing data type 

In [59]:
n.dtype

dtype('float64')

In [61]:
myarr.dtype

dtype('float32')

In [63]:
myarr.size

12

In [65]:
myarr.ndim

2

In [67]:
myarr.shape

(4, 3)

In [97]:
 myarr = np.array([[1,3,4],[6,7,8],[9,3,12],[21,13,29]])
reshaped = myarr.reshape(6,2) # 6 rows and 2 columns
reshaped


array([[ 1,  3],
       [ 4,  6],
       [ 7,  8],
       [ 9,  3],
       [12, 21],
       [13, 29]])

In [91]:
myarr.flatten() # converts into one dimensional  array 

array([ 1,  3,  4,  6,  7,  8,  9,  3, 12, 21, 13, 29])