In [2]:
import numpy as np


In [3]:
arr = np.array([1,12,34,5,43,54],dtype = np.int64)

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr.astype("float64")

array([ 1., 12., 34.,  5., 43., 54.])

In [6]:
import sys
l1 = list(range(1_000_000))
l2 = np.array(l1)
list_storage = print(sys.getsizeof(l1) + sum(sys.getsizeof(x) for x in l1))
np_storage = print(l2.nbytes)

36000056
4000000


In [7]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64) 
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [8]:
arru = np.array([1,2,3,4,5,6,7], dtype = np.float32)


In [9]:
print(arru)

[1. 2. 3. 4. 5. 6. 7.]


In [10]:
print(arru.dtype)

float32


In [11]:
arru.astype("float64")

array([1., 2., 3., 4., 5., 6., 7.])

In [12]:
arru.dtype

dtype('float32')

In [13]:
# complex numbers 
complex_arr = np.array([1+2j, 3+4j, 5+6j], dtype = 'complex128')
print(complex_arr)

[1.+2.j 3.+4.j 5.+6.j]


In [14]:
complex_arr.sum()

(9+12j)

In [15]:
array = np.array([1,2,3,4,5], dtype = np.int64)

In [16]:
array.dtype

dtype('int64')

In [17]:
array.astype('float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [18]:
array.dtype

dtype('int64')

In [19]:
array.dtype

dtype('int64')

In [23]:
arru = np.array([1,2,3,4,5,6,7,8 ],dtype = np.int64)

In [27]:
arru.dtype

dtype('int64')

In [29]:
arr.astype(np.int32)

array([ 1, 12, 34,  5, 43, 54])

In [31]:
arr.dtype

dtype('int64')

In [33]:
arru.dtype

dtype('int64')