In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
flat[3:5] # syntax == flat[index : len(array)]

array([4, 5])

In [6]:
flat[2:5] # just same as [0:5]

array([3, 4, 5])

In [7]:
flat[3:12] # same as [3:12] (st(index) : len(array)

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
len(flat)

12

In [9]:
flat[:: 2]  # every 2nd element 

array([ 1,  3,  5,  7,  9, 12])

In [10]:
# slicing returns a view, not a copy (important)...
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
b = flat[3:7] 

In [12]:
b

array([4, 5, 6, 7])

In [13]:
b[1]= 56

In [14]:
b

array([ 4, 56,  6,  7])

In [15]:
flat

array([ 1,  2,  3,  4, 56,  6,  7,  8,  9, 11, 12, 13])

In [16]:
array = np.array([1,2,3,4,5,6,7])
b = array[2:5].copy()  # using copy so changes cannot effect the orignal array
b[0] = 34

array

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
b

array([34,  4,  5])

In [18]:
fancy = np.array([1,2,3,4,5,6,7,8,9,19])

In [19]:
fancy[[2,4,6]]  # fancy slicing of above array fancy 

array([3, 5, 7])

In [20]:
fancy[fancy>5] # boolean masking ( providing a condition)

array([ 6,  7,  8,  9, 19])

In [21]:
arru = np.array([1,2,3,4,5,6])
arru[[1,3,5]]    # using fancy indexing to extract even numbers

array([2, 4, 6])

In [22]:
arru = np.array([1,2,3,4,5,6,7,8,9,])

In [23]:
reshape = arru.reshape(3,3)

In [24]:
reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
#masking numbers greater than 50
more = np.arange(1,100,6)  # output : [1,7,13,...so on]


In [26]:
more[more>50]  # condition greater than 50 

array([55, 61, 67, 73, 79, 85, 91, 97])

In [27]:
lol = np.array([1,2,3,4,5,6,7,8,9])
b = lol[2:6]
print(b)
print(lol)

[3 4 5 6]
[1 2 3 4 5 6 7 8 9]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])