In [1]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
np.sum(arr, axis=1) #if axis is 0 (vertical moment) or 1 (horizontal moment)

array([ 6, 15, 24])

In [3]:

np.sum(arr, axis=0) 

array([12, 15, 18])

In [4]:
two_d = np.array([[11,12,13],
          [1,2,3],
          [4,5,6]])
two_d


array([[11, 12, 13],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [5]:
np.sum(two_d, axis=0) 

array([16, 19, 22])

In [6]:
np.sum(two_d, axis=1) 

array([36,  6, 15])

In [7]:
# multidimensional indexing in numpy
two_d = np.array([[11,12,13], #0
                  [1,2,3],    #1
                  [4,5,6]])   #2
                  #0#1#2            

In [8]:
two_d[0][1]

12

In [9]:
two_d[0,1]

12

In [10]:
two_d[1:3, 0:2]  # [rows, columns] 2nd row and 3rd row , first column and 2nd column

array([[1, 2],
       [4, 5]])

In [11]:
arr3D = np.array([[[1, 2, 3], 
                   [4, 5, 6]],
                  [[7, 8, 9], 
                   [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [12]:
arr3D[1,0,2]  # output is 9 [depth,row,column] 

9

In [13]:
arr3D[:,1,:] # get the 2nd row from both sheets

array([[ 4,  5,  6],
       [10, 11, 12]])

In [14]:
arr3D[:,:,0]  # : printing 1st column of both 2d arrays

array([[ 1,  4],
       [ 7, 10]])

In [15]:
arr3D[:,1,1] # printing 2nd row and 2nd column of 2d arrays

array([ 5, 11])

In [16]:
# : when you use this all list rows and columns included in slicing

In [17]:
arr3D[0,1,0] 

4

In [18]:
print(arr3D[:,0,0]) # [1,7] output

[1 7]


In [19]:
arry2D = np.array([[1,2,3],  # practice 
                   [4,5,6],
                   [7,8,9]])
                   
print(arry2D[:,0]) # [rows,columns]

[1 4 7]


In [20]:
# you can also change the value in the 3d array by using arrayname[depth,rows,columns]=value.

In [21]:
print(arr3D[:,:,1])

[[ 2  5]
 [ 8 11]]


In [22]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
print(arr3D[0,0,:])

[1 2 3]
