In [1]:
# using python list
import numpy as np # all data scientist use numpy as np
import time

size = 1_000_000
l1 = list(range(size))
l2 = list(range(size))  # [1,2,....99999] each list

start = time.time()# to note down the start time

add = [x+y for x,y in zip(l1, l2)]  # adding each element of l1 and l2 by using list comprehension.
end = time.time()
print( end - start)

0.1105647087097168


In [2]:
# using numpy array
import numpy as np # all data scientist use numpy as np
import time

size = 1_000_000
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()# to note down the start time

add = l1 + l2
end = time.time() # to note down the end time
print( end - start)


0.031539201736450195


In [3]:
l1 = [1,45,3,10]

In [4]:
l2 = [6,45,89,43]

In [5]:
list(zip(l1,l2))


[(1, 6), (45, 45), (3, 89), (10, 43)]

In [6]:
oned = np.array([1,2,3,4,5,6])  # mostly numpy array uses numbers deeply 
print(oned)

[1 2 3 4 5 6]


In [7]:
oned.shape

(6,)

In [8]:
# 2d array :--
arr = np.array([[1,2,3],[7,8,9],[4,5,6,]])# each row contain same number of elements
print(arr)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [9]:
type(arr)  

numpy.ndarray

In [10]:
arr.shape # shows rows and columns

(3, 3)

In [11]:
import sys
import numpy as np

# Create a list of 1000 numbers
list_data = list(range(1000))

# Convert it to a NumPy array
numpy_data = np.array(list_data)

# Calculate total memory used by Python list (list object + all elements)
list_size = sys.getsizeof(list_data) + sum(sys.getsizeof(x) for x in list_data)

# Calculate total memory used by NumPy array (just data, since type is fixed)
numpy_size = numpy_data.nbytes

# Print memory usage
print("Python list size:", list_size, "bytes")
print("NumPy array size:", numpy_size, "bytes")


Python list size: 36056 bytes
NumPy array size: 4000 bytes


In [12]:
# for practice and understand the concept of memory efficiency better
list_data = list(range(2000))
numpy_data = np.array(list_data)
ls_size = sys.getsizeof(list_data) + sum(sys.getsizeof(x) for x in list_data)# used generator expression
np_size = numpy_data.nbytes
print(ls_size,"bytes")
print(np_size,"bytes")

72056 bytes
8000 bytes


In [13]:
lst1 = list(range(1_000_000))
st_time = time.time()
lst_sq = [x ** 2 for x in lst1]
end_time = time.time()
print(end_time-st_time)

0.1114194393157959


In [14]:
arr1 = np.array(lst1)
st_time = time.time()
np_sq = arr1 ** 2
end_time = time.time()
print(end_time-st_time)

0.0038323402404785156


In [23]:
arr1 = np.arange(10,101)  # practice excersise
print(arr1)
print(arr1.shape)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
(91,)


In [27]:
l1 = list(range(100_000))
l2 = list(range(100_000))
st_time = time.time()
mul = [x*y for x,y in zip(l1,l2)]
end_time = time.time()
print(end_time-st_time)

       


0.004984617233276367


In [29]:
l1 = np.array(list(range(100_000)))
l2 = np.array(list(range(100_000)))
st_time = time.time()
mul = l1*l2
end_time = time.time()
print(end_time-st_time)

       


0.0020139217376708984


In [39]:
one_million = np.array(range(1_000_000)) # alternate version np.arange(1_000_000)
million_np_array_size = one_million.nbytes
print(million_np_array_size)
print(one_million)

4000000
[     0      1      2 ... 999997 999998 999999]
